{"uuid": "3630be0a-8f86-429d-aca9-4d1ee119b50e", "children": ["685e1a2a-6f24-452b-9fab-b1ed5944aac0"], "befores": [{"name": "_xunit_setup_method_fixture_TestTestSenaryo5", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=126.0.6478.127)\nStacktrace:\n\tGetHandleVerifier [0x00007FF6517EEEA2+31554]\n\t(No symbol) [0x00007FF651767ED9]\n\t(No symbol) [0x00007FF65162872A]\n\t(No symbol) [0x00007FF6515FD995]\n\t(No symbol) [0x00007FF6516A44D7]\n\t(No symbol) [0x00007FF6516BC051]\n\t(No symbol) [0x00007FF65169CDD3]\n\t(No symbol) [0x00007FF65166A33B]\n\t(No symbol) [0x00007FF65166AED1]\n\tGetHandleVerifier [0x00007FF651AF8B1D+3217341]\n\tGetHandleVerifier [0x00007FF651B45AE3+3532675]\n\tGetHandleVerifier [0x00007FF651B3B0E0+3489152]\n\tGetHandleVerifier [0x00007FF65189E776+750614]\n\t(No symbol) [0x00007FF65177375F]\n\t(No symbol) [0x00007FF65176EB14]\n\t(No symbol) [0x00007FF65176ECA2]\n\t(No symbol) [0x00007FF65175E16F]\n\tBaseThreadInitThunk [0x00007FF936A6257D+29]\n\tRtlUserThreadStart [0x00007FF9377EAF28+40]\n\n", "trace": "  File \"C:\\Users\\Ömer Vardar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\Ömer Vardar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Ömer Vardar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Ömer Vardar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Ömer Vardar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 877, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Ömer Vardar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\python.py\", line 815, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"C:\\Users\\Ömer Vardar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\python.py\", line 709, in _call_with_optional_argument\n    func(arg)\n  File \"c:\\Users\\Ömer Vardar\\Desktop\\TobetoAutomatedTesting\\test_testsenaryo5.py\", line 17, in setup_method\n    self.login(\"furkangmsky@gmail.com\", \"Furkan-1445\")\n  File \"c:\\Users\\Ömer Vardar\\Desktop\\TobetoAutomatedTesting\\test_testsenaryo5.py\", line 40, in login\n    WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.XPATH, \"//button[@type='submit']\"))).click()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Ömer Vardar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 96, in until\n    value = method(self._driver)\n            ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Ömer Vardar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 363, in _predicate\n    target = driver.find_element(*target)  # grab element at locator\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Ömer Vardar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 741, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Ömer Vardar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Ömer Vardar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1719651104968, "stop": 1719651127957}], "start": 1719651104968, "stop": 1719651128024}